# Generated by Django 4.1 on 2022-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
